// Fields exposed as stored columns, excluding computed GraphQL resolvers.
export const databaseFields: Record<string, string[]> = {
  std_logs: ['id', 'createdAt', 'message', 'level', 'data', 'deletedAt'],
  jobs: ['id', 'createdAt', 'type', 'isRunning', 'deletedAt'],
  industries: ['id', 'createdAt', 'name', 'deletedAt'],
  sectors: ['id', 'createdAt', 'name', 'deletedAt'],
  companies: [
    'id',
    'createdAt',
    'name',
    'cik',
    'isin',
    'cusip',
    'employees',
    'address',
    'description',
    'sectorId',
    'industryId',
    'deletedAt',
  ],
  users: [
    'id',
    'createdAt',
    'deletedAt',
    'id',
    'username',
    'incomePerYear',
    'incomeTaxRate',
    'salaryChargeRate',
    'currency',
  ],
  followed_security_groups: [
    'id',
    'createdAt',
    'deletedAt',
    'name',
    'index',
    'type',
    'userId',
  ],
  followed_securities: [
    'id',
    'createdAt',
    'deletedAt',
    'technicalAnalysis',
    'alias',
    'index',
    'followedSecurityGroupId',
    'securityId',
  ],
  historical_prices: [
    'id',
    'createdAt',
    'deletedAt',
    'date',
    'open',
    'high',
    'low',
    'close',
    'volume',
    'change',
    'changePercent',
    'securityId',
  ],
  user_accounts: [
    'id',
    'createdAt',
    'deletedAt',
    'name',
    'type',
    'provider',
    'balance',
    'userId',
  ],
  user_account_securities: [
    'id',
    'createdAt',
    'deletedAt',
    'name',
    'volume',
    'openPrice',
    'currency',
    'openedAt',
    'profit',
    'externalId',
    'securityId',
    'userAccountId',
  ],
  securities: [
    'id',
    'createdAt',
    'deletedAt',
    'ticker',
    'currency',
    'type',
    'marketStatus',
    'fiscalYearEndMonth',
    'currentPrice',
    'dayChange',
    'dayChangePercent',
    'weekChange',
    'weekChangePercent',
    'extendedHoursPrice',
    'extendedHoursChangePercent',
    'high52Week',
    'low52Week',
    'marketCapitalization',
    'sharesOutstanding',
    'companyId',
  ],
  financial_items: [
    'id',
    'createdAt',
    'deletedAt',
    'slug',
    'label',
    'type',
    'statement',
    'unit',
    'unitType',
    'index',
    'isMain',
    'latexDescription',
    'direction',
  ],
  financials: [
    'id',
    'createdAt',
    'deletedAt',
    'value',
    'year',
    'period',
    'reportDate',
    'isEstimate',
    'securityId',
    'sectorId',
    'financialItemId',
  ],
  earnings: [
    'id',
    'createdAt',
    'deletedAt',
    'date',
    'fiscalYear',
    'fiscalQuarter',
    'time',
    'epsEstimate',
    'eps',
    'revenue',
    'revenueEstimate',
    'epsSurprisePercent',
    'revenueSurprisePercent',
    'callTranscript',
    'securityId',
  ],
  news: [
    'id',
    'createdAt',
    'deletedAt',
    'date',
    'type',
    'title',
    'content',
    'website',
    'url',
    'securityId',
  ],
  forex: [
    'id',
    'createdAt',
    'deletedAt',
    'fromCurrency',
    'toCurrency',
    'exchangeRate',
  ],
  user_transactions: [
    'id',
    'createdAt',
    'deletedAt',
    'name',
    'value',
    'category',
    'type',
    'frequency',
    'date',
    'userId',
  ],
}
