name: client.publish

on:
  release:
    types: [published]

jobs:
  publish_to_registry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: publish
        uses: docker/build-push-action@v3
        with:
          context: client
          push: true
          cache-from: type=registry,ref=fcote/merlin-client:latest
          cache-to: type=inline
          tags: fcote/merlin-client:latest
