name: scheduler.build

on:
  push:
    branches: [ dev ]
    paths:
      - 'scheduler/**'
  pull_request:
    branches: [ dev ]
    paths:
      - 'scheduler/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.1'

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: scheduler

      - name: build
        run: go build .
        working-directory: scheduler