name: scheduler.build

on:
  push:
    branches: [ dev ]
    paths:
      - 'scheduler/**'
  pull_request:
    branches: [ dev ]
    paths:
      - 'scheduler/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: setup golang
        uses: actions/setup-go@v7
        with:
          go-version-file: 'scheduler/go.mod'

      - name: lint
        uses: golangci/golangci-lint-action@v9
        with:
          working-directory: scheduler

      - name: test
        run: go test ./...
        working-directory: scheduler

      - name: build
        run: go build .
        working-directory: scheduler
