name: server.publish

on:
  release:
    types: [published]

jobs:
  publish_to_registry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: publish
        uses: docker/build-push-action@v2
        with:
          context: server
          push: true
          cache-from: type=registry,ref=fcote/merlin-server:latest
          cache-to: type=inline
          tags: fcote/merlin-server:latest
